=== MariaGalaviz/LALIGA/LALIGA/LALIGA.dtd
<!ELEMENT LALIGA (JUEGO+)>
        <!ELEMENT JUEGO (FECHA, EQUIPO_LOCAL, EQUIPO_VISITANTE, RESULTADO, ESTADISTICAS)>
        <!ELEMENT FECHA (#PCDATA)>
        <!ELEMENT EQUIPO_LOCAL (#PCDATA)>
        <!ELEMENT EQUIPO_VISITANTE (#PCDATA)>
        <!ELEMENT RESULTADO (#PCDATA)>
        <!ELEMENT ESTADISTICAS (POSESION, TIROS_PORTERIA, FALTAS)>
        <!ELEMENT POSESION (#PCDATA)>
        <!ELEMENT TIROS_PORTERIA (#PCDATA)>
        <!ELEMENT FALTAS (#PCDATA)>

=== MariaGalaviz/LALIGA/LALIGA/resultadosLALIGA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LALIGA SYSTEM "LALIGA.dtd">
<LALIGA>
    <JUEGO>
        <FECHA>15-09-2024</FECHA>
        <EQUIPO_LOCAL>Real Madrid</EQUIPO_LOCAL>
        <EQUIPO_VISITANTE>FC Barcelona</EQUIPO_VISITANTE>
        <RESULTADO>2-1</RESULTADO>
        <ESTADISTICAS>
            <POSESION>55% - 45%</POSESION>
            <TIROS_PORTERIA>6 - 4</TIROS_PORTERIA>
            <FALTAS>12 - 14</FALTAS>
        </ESTADISTICAS>
    </JUEGO>
    <JUEGO>
        <FECHA>16-09-2024</FECHA>
        <EQUIPO_LOCAL>Sevilla FC</EQUIPO_LOCAL>
        <EQUIPO_VISITANTE>Atletico Madrid</EQUIPO_VISITANTE>
        <RESULTADO>1-1</RESULTADO>
        <ESTADISTICAS>
            <POSESION>48% - 52%</POSESION>
            <TIROS_PORTERIA>3 - 5</TIROS_PORTERIA>
            <FALTAS>10 - 9</FALTAS>
        </ESTADISTICAS>
    </JUEGO>
</LALIGA>
